# there is an issue with this: conda build does "git-clone --recursive"
# but that fails, because the .gitmodules file doesn't use the "https:"
# form for the submodules, it uses the "git@" form, and the psrel
# account doesn't have permissions (or even a github account).  and
# even the "https:" version seems to prompt for a password when run
# as psrel.  for now I'm working around this by doing conda-build as
# a user with read permission, not psrel. -cpo

{% set version = "1.0.0" %}

package:
  name: wave8
  version: {{ version }}

source:
  #git_url: https://github.com/slaclab/wave8.git
  #git_url: git@github.com:slaclab/wave8.git
  #git_tag: v{{ version }}
  #git_tag: l2si-rogue
  path: ../../../wave8-pkg

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #script: git submodule update --recursive; cd firmware/common/python; $PYTHON setup.py install  --single-version-externally-managed --record=record.txt
  script: cd firmware/python; ${PYTHON} setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
