language: minimal
sudo: required

services:
  - docker

env:
  global:
  - DOCKER_USERNAME: slacmachineaccount
  - secure: eII/OyQZBvt37LtmqpuGxudX9kxZoVEpPAAuUA2MBC5KFRw5e66tqrNZqZgITI1tIfP4s+P4/7JDoyXjxWNExAIBHisdZiJ28y2j0tjKpcASNee2d2PRr4ZCJi9nvHdfRH2V6U9XAiksiK3GVymWQS+DInGLhD/QPRPT5X9x9dZUxgTqgYwBCCR2OU6XVu6S+hqxSBh/IMgfQauZsCDebYKJkZAu0TUT80NJ476Dg/VmU69of9IoDfhgJyd8uAJW2JWY8PcJcF/YaG0J+I5+bZMWp4lG3QKJVlDD2zLIAK8b/09qW77CX5WxndFX5KWtD1vPQUEh4ja6TpHEEOreY/WLCZ5zmgpiecARfHe3HBdA6gJ7Uwo0xbP82YtTjh9W5QAl2m6WoC/FNgLcSc34aCjRcOtHZ2hZ9c7RrGCnoyog2h5FALZdE/ZiafgvQWOsOBl/hwzCMTZpsxiLkW7d8XFuB2mQazQA1DiIXHC974s7I4I+NopcTD0ei3zuvb/GYV3QLlgJfvlB16pjYqbA4WYMpNKqeEIQezG0ldmqO4QIPmOWc3Ojqv14s38XEvogNfxzQeXpnnr5dAGMDADS18hCIRC1oMV3csxxtu/OBW55A8jstgKc+dgZvcIPirOO7gyF+q0Jhv1X+yQSW46j8jY3gpM7e+cUfpwjSqE3ZoI=
  matrix:
    - PYVER=2.7
    - PYVER=3.6

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./docker/build_all.sh
