channels:
  - file:///cds/sw/ds/ana/conda2/channels/local-lcls-ii
  - lcls-ii
  - conda-forge
  - defaults
  - tidair-tag # rogue
  - tidair-packages # pcas for rogue
dependencies:
  - python=3.7
  - psdaq
  - ami
  - ipywidgets
  - ipympl
