package:
  name: ami
  version: 0.0.1

source:
  git_url: https://github.com/slac-lcls/ami.git

requirements:
  build:
    - python
  run:
    - pytest-asyncio
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - asyncqt
