{% set version = "2.0.0" %}

package:
  name: ami
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/ami.git
  git_tag: master

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - setuptools
    - python
    - pytest-runner
  run:
    - python
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - qtpy
    - asyncqt
    - amityping
    - mypy
