{% set version = "1.0.1" %}

package:
  name: ami
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/ami.git
  git_tag: v{{ version }}

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - pytest-asyncio
    - pytest-qt
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - asyncqt
    - amityping
    - mypy
    - mypy_extensions
