package:
  name: ami
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/ami.git

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  host:
    - setuptools
    - python
    - pytest-runner
  run:
    - python
    - dill
    - pyzmq
    - pyqtgraph
    - networkfox
    - psana
    - ipython
    - qtpy
    - asyncqt
    - amityping
    - mypy
    - numba
    - h5py # optional: to use h5 source
    - pyarrow # optional: better pickling for arrays
    - scipy # optional: more algorithms
    - pytest-qt # optional: for test
