{% set version = "4.13.2" %}

package:
  name: pcas
  version: {{ version }}

source:
  git_url: https://github.com/epics-modules/pcas.git
  git_tag: v{{ version }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]
  host:
    - epics-base >=7
  run:
    - epics-base >=7
