{% set version = "2.6.4" %}

package:
  name: amccarriercore
  version: {{ version }}

#source:
  # cpo: like with pcieapps, get smudge errors when we do this
  #git_url: https://github.com/slaclab/amc-carrier-core.git
  #git_tag: v{{ version }}
  #git_tag: pre-release

build:
  noarch: python
  # see comment in "source" section
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
