{% set version = "10.2.63" %}

package:
  name: libpsm2
  version: {{ version }}

source:
  - git_url: https://github.com/01org/opa-psm2
    git_rev: a1cb2adaedb3bd3fa84dc0bcf66333b2e598d777
  - path: ./hfi1_user.h
  - patches:
    - makefiles.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libuuid-devel') }}
  host:
    - pkg-config
