{% set version = "0.0.6" %}

package:
  name: networkfox
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/networkfox.git
  git_tag: v{{ version }}

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
    - networkx
