{% set name = "pytest-asyncio" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c54866f3cf5dd2063992ba2c34784edae11d3ed19e006d220a3cf0bfc4191fcb

build:
  number: 1001
  skip: True  # [py2k]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pytest >=5.4.0

test:
    imports:
      - pytest_asyncio

about:
  home: http://github.com/pytest-dev/pytest-asyncio
  license: Apache 2.0
  license_file: LICENSE
  #license_file: LICENSE # License file is missing in package
  summary: 'Pytest support for asyncio'

  dev_url: https://github.com/pytest-dev/pytest-asyncio
