{% set version = "1.0.6" %}

package:
  name: psana
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]

  host:
    - python
    - numpy
    - cython
    - psalg

  run:
    - python
    - numpy
    - matplotlib
    - xtcdata
    - psalg
    - requests
    - mpi   # [osx]
    - mpi4py
    - mongodb
    - pymongo
    - amityping
    - mypy_extensions
    - bitstruct
