package:
  name: psana
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/lcls2.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]

  host:
    - python
    - numpy
    - cython
    - psalg

  run:
    - python
    - numpy
    - matplotlib
    - xtcdata
    - psalg
    - requests
    - mpi   # [osx]
    - mpi4py
    - mongodb
    - pymongo
    - amityping
    - mypy_extensions
    - h5py>=2.10 # needed by small-h5 writer
    - pyzmq
    - psmon
    - h5py
    - krtc
    - legion
    - opencv # for xtcav
    - scikit-learn # for xtcav and tmo pop alg
    - pyabel # for tmo pop alg
