# there is an issue with this: conda build does "git-clone --recursive"
# but that fails, because the .gitmodules file doesn't use the "https:"
# form for the submodules, it uses the "git@" form, and the psrel
# account doesn't have permissions (or even a github account).  and
# even the "https:" version seems to prompt for a password when run
# as psrel.  for now I'm working around this by doing conda-build as
# a user with read permission, not psrel. -cpo

{% set version = "0.0.1" %}

package:
  name: pcieapps
  version: {{ version }}

#source:
  # cpo: thought this should work, but get some "smudge" errors.
  # it seems to work when I do the git checkout in build.sh though.
  # I don't understand why.
  # Error downloading object: firmware/targets/RateTestKcu1500/images/RateTestKcu1500-0x00000022-20181024122011-rherbst-2bf6b0a0_primary.mcs.gz (87d2cb3): Smudge error: Error downloading firmware/targets/RateTestKcu1500/images/RateTestKcu1500-0x00000022-20181024122011-rherbst-2bf6b0a0_primary.mcs.gz (87d2cb39d6d0ada9bf2d34bdf375667e514ed24ad789d27ce62fc8166cb89a5b): batch request: missing protocol: "file:///reg/neh/home/cpo/conda-bld/git_cache/github.com/slaclab/lcls2-pcie-apps.git/info/lfs"

  #git_url: https://github.com/slaclab/lcls2-pcie-apps.git
  #git_tag: v{{ version }}
  #git_tag: pre-release

build:
  noarch: python
  # see comment in "source" section
  #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  #script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
  run:
    - python
