package:
  name: transitions
  version: 0.6.8

source:
  url: https://files.pythonhosted.org/packages/ca/29/e394e452ce6e8a7d8c0ff1ab9ca36f939859f04017506754bc3c7f74d380/transitions-0.6.8.tar.gz

requirements:
  build:
    - python
  run:
    - python
