{% set version = "0.5.3" %}

package:
  name: yaml-cpp
  version: {{ version }}

source:
  git_url: https://github.com/jbeder/yaml-cpp.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
