{% set version = "3.3" %}

package:
  name: infinipath-psm
  version: {{ version }}

source:
  - git_url: https://github.com/01org/psm
    git_rev: 604758e76dc31e68d1de736ccf5ddf16cb22355b
  - patches:
    - ./0001-Extend-buffer-for-uvalue-and-pvalue.patch
    - ./0001-Include-sysmacros.h.patch
    - ./disable-Werror.patch
    - ./remove-executable-permissions-for-header-files.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libuuid-devel') }}
