# cpo modified this recipe from the default recipe in
# anaconda.org/tidair-tag:
# - remove epics/pyepics/pydm/pcas from build/run dependencies
# - change pkg name to rogue-ne

package:
  name: rogue-ne
  version: {{ environ.get('GIT_DESCRIBE_TAG') }}

source:
  git_url: https://github.com/slaclab/rogue.git

build:
   number: {{ environ.get('GIT_DESCRIBE_NUMBER',0) }}

requirements:
   build:
     - python
     - boost
     - {{ compiler('c') }}
     - {{ compiler('cxx') }}
     - git
     - cmake
     - make
     - bzip2
     - zeromq
     - numpy
   host:
     - python
     - boost
     - bzip2
     - zeromq
     - numpy
   run:
     - python
     - {{ pin_compatible('boost', min_pin='x.x', max_pin='x.x')}}
     - boost
     - bzip2
     - zeromq
     - numpy
     - ipython
     - pyyaml
     - jsonpickle
     - pyzmq
     - parse
     - click
     - pyqt
     - sqlalchemy
     - pyserial

about:
   home: https://github.com/slaclab/rogue
   license: SLAC Open License
   license_file: LICENSE.txt
   summary: SLAC Python Based Hardware Abstraction And Data Acquisition System
