{% set version = "3.2.28" %}

package:
  name: libnl3
  version: {{ version }}

source:
  url: http://www.infradead.org/~tgr/libnl/files/libnl-{{ version }}.tar.gz
  patches:
    - ./0001-compare-v4-addr-rh1370503.patch
    - ./0002-msg-peek-by-default-rh1396882.patch
    - ./typedef.patch
    - ./in6.patch

build:
  number: 0

requirements:
  build:
    - python
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:  
    - flex
    - bison
    - libtool
    - autoconf
    - automake 
    - pkg-config
