{% set version = "0.1" %}

package:
  name: psalg
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - xtcdata
    - rapidjson
    - libcurl
  run:
    - xtcdata
    - libcurl
