{% set version = "1.2.0" %}

package:
  name: psalg
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - llvm-openmp           # [osx]
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]
  host:
    - python
    - xtcdata
    - rapidjson
    - libcurl
  run:
    - python
    - xtcdata
    - libcurl
    - llvm-openmp   # [osx]
