package:
  name: psalg
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/lcls2.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
  host:
    - python
    - xtcdata
    - rapidjson
    - libcurl
    - roentdek # [linux]
  run:
    - python
    - xtcdata
    - libcurl
    - llvm-openmp # [osx]
    - roentdek # [linux]
