package:
  name: psalg
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/lcls2.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - llvm-openmp           # [osx]
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]
  host:
    - python
    - xtcdata
    - rapidjson
    - libcurl=7.67.0 # cpo: hack to prevent conflict with pykerberos depending on old krb5
    - roentdek # [linux]
  run:
    - python
    - xtcdata
    - libcurl
    - llvm-openmp   # [osx]
    - roentdek # [linux]
