{% set version = "0.6.0" %}

package:
  name: prometheus-cpp
  version: {{ version }}

source:
  git_url: https://github.com/jupp0r/prometheus-cpp.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cmake
