{% set version = "0.7.0" %}

package:
  name: prometheus-cpp
  version: {{ version }}

source:
  git_url: https://github.com/jupp0r/prometheus-cpp.git
  git_rev: v{{ version}}

build:
  number: 2

requirements:
  build:
    - cmake
  host:
    - zlib
    - libcurl
  run:
    - zlib
    - libcurl
