#{% set version = "1.4.2" %}
#{% set version = "1.10.0" %}
{% set version = "1.7.1" %}

package:
  name: libfabric
  version: {{ version }}

source:
  - git_url: https://github.com/ofiwg/libfabric.git 
    git_rev: v{{ version }}
  - path: ./ib_user_verbs.h

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libuuid-devel') }}
  host:
    - libnl
#    - libnl3
    - rdma-core
#    - infinipath-psm
#    - libpsm2
  run:
    - libnl
#    - libn3
    - rdma-core
#    - infinipath-psm
#    - libpsm2
