#{% set version = "1.4.2" %}
{% set version = "1.7.1" %}

package:
  name: libfabric
  version: {{ version }}

source:
  - url: https://github.com/ofiwg/libfabric/releases/download/v{{ version }}/libfabric-{{ version }}.tar.bz2
  - path: ./ib_user_verbs.h

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libuuid-devel') }}
  host:
    - libnl
    - libnl3
    - rdma-core
#    - infinipath-psm
#    - libpsm2
  run:
    - libnl
    - libnl3
    - rdma-core
#    - infinipath-psm
#    - libpsm2
