{% set version = "7.0.1" %}

package:
  name: epics-base
  version: {{ version }}

source:
  git_url: https://github.com/epics-base/epics-base.git
  git_rev: 7.0
  patches:
    - config_readline.diff
    - config_common.diff

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - perl
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
