{% set version = "7.0.3" %}

package:
  name: epics-base
  version: {{ version }}

source:
  git_url: https://github.com/epics-base/epics-base.git
  git_tag: R{{ version }}
  patches:
    - config_common.diff      # [linux]
    - config_common_osx.diff  # [osx]

build:
  number: 0

requirements:
  build:
    - perl
    - readline
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - readline
  run:
    - readline
