# a dummy package since pyca not available for py2
package:
  name: pyca
  version: 1.0.0

requirements:
  build:
    - python {{ environ.get('PY_VER') }}
  run:
    - python {{ environ.get('PY_VER') }}
