{% set version = "0.5.10" %}

package:
  name: legion
  version: {{ version }}

source:
  git_url: https://gitlab.com/StanfordLegion/legion.git
  git_rev: python

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - mpich
    - python {{ environ.get('PY_VER') }}
  run:
    - cffi
    - mpich
    - numpy
    - python {{ environ.get('PY_VER') }}
