{% set version = "0.5.17" %}

package:
  name: legion
  version: {{ version }}

source:
  git_url: https://gitlab.com/StanfordLegion/legion.git
  git_rev: cmake-gasnet-private-dependency-dcr

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - USE_CUDA
    - USE_GASNET
    - CONDUIT
requirements:
  build:
    - cmake
    - python {{ environ.get('PY_VER') }}
  run:
    - cffi
    - numpy
    - python {{ environ.get('PY_VER') }}
