{% set version = "0.5.3" %}

package:
  name: legion
  version: {{ version }}

source:
  git_url: https://gitlab.com/StanfordLegion/legion.git
  git_rev: python

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
    - python 3.6
  run:
    - cffi
    - numpy
    - python 3.6
