{% set version = "0.5.19" %}

package:
  name: legion
  version: {{ version }}

source:
  git_url: https://gitlab.com/StanfordLegion/legion.git
  git_rev: control_replication
  patches:
    - legion_cffi_build_gcc.patch

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - USE_CUDA
    - USE_GASNET
    - CONDUIT
requirements:
  build:
    - cmake
    - make
    - perl
    - zlib
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cffi
  run:
    - cffi
    - numpy
    - python
    - zlib
