{% set version = "0.1.0" %}

package:
  name: legion
  version: {{ version }}

source:
  git_url: https://github.com/StanfordLegion/legion.git
  git_rev: python

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
  run:
    - cffi
    - numpy
