{% set version = "1.2.0" %}

package:
  name: psdaq
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/lcls2.git
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
requirements:
  build:
    - cmake
  host:
    - xtcdata
    - psalg
    - python
    - cpsw
    - libfabric
    - epics-base
    - zeromq
  run:
    - xtcdata
    - psalg
    - python
    - cpsw
    - libfabric 
    - epics-base
    - transitions
    - zeromq
    - prometheus_client
