package:
  name: psdaq
  version: '{{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}'

source:
  git_url: https://github.com/slac-lcls/lcls2.git

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('libibverbs') }}
    - {{ cdt('libibverbs-devel') }}
    - {{ cdt('libnl') }}
    - {{ cdt('librdmacm') }}
    - {{ cdt('librdmacm-devel') }}
  host:
    - xtcdata
    - psalg
    - python
    - cpsw
    - libfabric
    - zeromq
    - p4p
  run:
    - xtcdata
    - psalg
    - python
    - cpsw
    - libfabric 
    - rapidjson
    - transitions
    - requests
    - transitions
    - zeromq
    - prometheus-cpp
    - prometheus_client
    - amityping
    - mypy
    - rogue-ne
    - bluesky
    - ophyd
    - p4p
    - lcls2_timetool
