package:
  name: psmon
  version: 1.0.0

source:
  git_url: https://github.com/slaclab/psmon.git

requirements:
  build:
    - python
  run:
    - python
    - pyqtgraph
    - pyzmq
    - numpy
    - matplotlib
    - ipython
