{% set version = "1.1.0" %}

package:
  name: amityping
  version: {{ version }}

source:
  git_url: https://github.com/slac-lcls/amityping.git
  git_tag: v{{ version }}

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: $PYTHON setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - mypy_extensions
