package:
  name: amityping
  version: {{ environ.get("GIT_DESCRIBE_TAG", "0.0.0") }}

source:
  git_url: https://github.com/slac-lcls/amityping.git

build:
  noarch: python
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - mypy_extensions
