{% set version = "3.0.0" %}

package:
  name: p4p
  version: {{ version }}

source:
  git_url: https://github.com/mdavidsaver/p4p.git
  git_tag: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - epics-base >=7
    - numpy
  run:
    - python
    - epics-base
    - numpy
  test:
    requires:
      - nose
    commands:
      - make nose
