{% set version = "3.3.2" %}

package:
  name: p4p
  version: {{ version }}

source:
  git_url: https://github.com/mdavidsaver/p4p.git
  git_tag: {{ version }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}   # [osx]
    - {{ compiler('cxx') }} # [osx]
  host:
    - python
    - epics-base >=7
    - numpy
  run:
    - python
    - {{ pin_compatible('epics-base', max_pin='x.x.x.x') }}
    - numpy
  test:
    requires:
      - nose
    commands:
      - make nose
