{% set version = "1.0.0" %} 
{% set build = "1" %}

package:
  name: libusdusb4
  version: {{ version }}

source:
  path: /reg/g/pcds/package/usdusb4

build:
  number: {{build}}

about:
  summary: "This is a shared library blob that is provided by US Digital for the USB4 encoder box"
